### PR TITLE
LoadWCSim Update

### PR DESCRIPTION
**Pull request by mnieslony**
Some updates to the `LoadWCSim` tool to make it resemble data more:

* Triggerwords can be specified in the configfile now (the same triggerword will be applied for all events)
* A PMT mask can be loaded to mask out dead PMTs when loading hits into ToolAnalysis
* The BeamStatus is now stores in the `BeamStatus` class in accordance with how it's done in data (not the `BeamStatusClass`, which is very similar)
* Neutron capture information was added to the ANNIEEvent (`MCNeutCap`,`MCNeutCapGammas`)
* The separation into sub-triggers was removed since we do not have this separation in data (just a stream of data for 2us/70us). The identification of activity within this acquisition window is then performed by the `ClusterFinder` tool.

### CODE REVIEW

**Comment by marc1uk** [comment]
Really nice PR that makes numerous coordinated changes across mutiple files in order to disable splitting wcsim triggers - a feature i actually think we should keep. :sweat_smile: Sorry.
But yeah, i think you've done all the hard work in identifying the set of changes to be made here, but I'd really prefer to turn this into a configuration toggle, rather than just comment it out. I fear that without expert knowledge and probably a lot of frustration, it would be difficult to undo these changes if we did want to restore this functionality in the future (which i expect we may).
The only thing that stands out as not being included in the set of changes related to merging the triggers is the addition of the neutron capture times, but i expect they would also need to be included in the timeline toggle (modify capture times similarly to the MCParticles loop at line 535) to shift them when processing subtriggers separately.

**Comment by marc1uk** [comment]
I also see that you've added new maps from [tube id to channelkey](https://github.com/ANNIEsoft/ToolAnalysis/blob/3543a7a1ac404efcb25fbb1c1efd608749544077/UserTools/LoadWCSim/LoadWCSim.cpp#L85) to the CStore, but there are [already such maps](https://github.com/ANNIEsoft/ToolAnalysis/blob/3543a7a1ac404efcb25fbb1c1efd608749544077/UserTools/LoadWCSim/LoadWCSim.cpp#L1324), so i'm lost why we now have two and what their difference is.

I haven't searched through the remaining tools to see where or how this is being used, but my gut feeling is we shouldn't have two maps, and if we need them, they should have clearer names.

**Comment by mnieslony** [comment]
Regarding the first point, the changes which were made were such that loading simulation files would result in the same data structure that we currently have in data. Since we don't have any real "triggers" in the data and just save all the hits that are encountered in one object, the `ANNIEEvent` Store should result in a similar data structure when loading simulation files, hence not subdividing triggers into different `Execute` steps. Otherwise it is also not possible to run the same toolchains on data and MC, since for example the `ClusterFinder` will then result in different outcomes in the two use cases. Any triggering/subtriggering (which is currently done by the `ClusterFinder`) should then potentially be done by downstream tools such that the same algorithms can also be used on data.
I agree that it would be a nice idea to keep the functionality and provide a configuration variable such that the user can decide whether subtriggers should be loaded in separate `Execute` steps or in the same `Execute` step.

Regarding the second point, a second map is needed because the channelkeys in the data do not match the channelkeys in the simulation. This is the case because in the data we have a static representation of channelkeys, while in the simulation case the channelkeys are assigned dynamically while loading the file. Maybe we should change this dynamic configuration in `LoadWCSim` and replace it with the `channelkeys` that we also use in data. In the meantime, two maps are needed in order to switch between data channelkeys and MC channelkeys (via WCSim IDs as an intermediate step). This is for example needed when calculating charge values in pC in the simulation based on the p.e. values and the measured gains, as you point out as a comment in #203.

**Comment by marc1uk** [comment]
OK, sounds good that we can keep the new merged triggers as the new default, but I would like to keep this functionality, since it exists and doesn't add much complexity overhead. (Perhaps we also ought to modify the WCSim [NHits threshold](https://github.com/ANNIEsoft/WCSim/blob/annie/macros/annie_daq.mac#L23) to 7 and [NHits window](https://github.com/ANNIEsoft/WCSim/blob/annie/macros/annie_daq.mac#L27) to 78us, but that's another topic).

> Maybe we should change this dynamic configuration in LoadWCSim and replace it with the channelkeys that we also use in data.

Yeah this seems like the obvious solution. The dynamic allocation of arbitrary channelkeys to each WCSim TubeID was put in place when we didn't have any fixed mapping of actual detector geometry. Now that we have that, it would make sense to have a fixed csv file mapping WCSim TubeID to real PMT channelkey, and have LoadWCSim assign those rather than just dealing out arbitrary ones with [ConsumeNextFreeDetectorKey](https://github.com/ANNIEsoft/ToolAnalysis/blob/81487bcc0c001a873ca20f8a1fbb64a2cb79a95d/UserTools/LoadWCSim/LoadWCSim.cpp#L982) and [ConsumeNextFreeChannelKey](https://github.com/ANNIEsoft/ToolAnalysis/blob/81487bcc0c001a873ca20f8a1fbb64a2cb79a95d/UserTools/LoadWCSim/LoadWCSim.cpp#L1009).

**Comment by mnieslony** [comment]
@marc1uk There is now a toggle in the `LoadWCSim` config file to either split subtriggers into different Execute steps or to load them all in one Execute step (default).
In addition, the channelkeys in the simulation now match the channelkeys in the data. In order to achieve this, there are three configuration files which map the PMT IDs of the tank PMTs, MRD PMTs, and FMV PMTs to the respective channelkeys. The default paths to the config files are hardcoded and can be changed via the configuration file, if needed.

**Comment by marc1uk** [comment]
Awesome! Looks good on the subtriggers front, and having just the unique channel keys and a set of maps for WCSim seems good. :+1: 

I could suggest that a check on `get_ok` [here](https://github.com/ANNIEsoft/ToolAnalysis/pull/202/files#diff-6766b0ea56d118c2f6037353fb8fcbdecae351b09609f351c9e194b6e84268dbR77) would allow a more graceful termination if no config file is provided, and an error printout and return false if [this](https://github.com/ANNIEsoft/ToolAnalysis/pull/202/files#diff-6766b0ea56d118c2f6037353fb8fcbdecae351b09609f351c9e194b6e84268dbR78) `file.is_open()` check fails would also be prudent (e.g. due to file not found). Similarly for the other subsystem channel key maps. 

One final thing on that splitting; does the newly added [neutron capture time](https://github.com/ANNIEsoft/ToolAnalysis/pull/202/files#diff-6766b0ea56d118c2f6037353fb8fcbdecae351b09609f351c9e194b6e84268dbR760) also need to shift according to this splittrigger system? It seems the neutron captures share global time, as per particles, so would need `EventTimeNs()` subtracted off in the case of split triggers. 

I'm afraid there were was also one other remark, this time from our repository and ToolFramework overlord - who was not a fan of the hard-coded [free channel key offset](https://github.com/ANNIEsoft/ToolAnalysis/pull/202/files#diff-d0f6eeac9a32c76de01dd11f270f16c906795b9690ef4628a327261be1eb0cb3R5).
I guess the idea here is that LAPPDs (or perhaps other simulation concepts) may still use `ConsumeNextFreeChannelKey()`, but the internal next free channel number doesn't know about the existing channels. 
I think perhaps the best solution here is to have the Detector constructor inform the Geometry that the key is taken. This would also allow it to check for clashes and throw and exception in case two Detectors were constructed with the same key. The passed key could also be an optional argument, in which case the constructor can internally invoke `ConsumeNextDetectorKey()` to generate one. The Detector constructor of course would need to take a pointer the geometry instance, and the same applies for the Channel class. 

:see_no_evil: sorry to bounce it back yet again...

**Comment by mnieslony** [comment]
Okay, the Geometry class was now reworked such that it also keeps track of all the channelkeys in addition to all the detectorkeys. This way, the `ConsumeNextFreeChannelKey()` functions can check which is the next available channel/detectorkey and can assign it to the respective detector (currently the LAPPDs). This removes the hard-coded channelkey offset which was previously introduced.

**Pull request merged**
