### PR TITLE
MRD paddle efficiency TGraph Update

### PR DESCRIPTION
**Pull request by mnieslony**
The `TH1`s for the MRD and FMV paddle efficiencies have been moved to `TEfficiency` objects for accurate handling of the efficiency errors (e.g. no error bars above 1.00).

I have used this functionality for a long time, just forgot to push these changes to the main repo.

In addition to the efficiency-related tools, the `LoadANNIEEvent` tool was extended such that it can skip files now in case they do not exist / the path is wrong.

### CODE REVIEW

**Comment by marc1uk** [comment]
Looks good michael, thanks. :+1: 
What's the situation with the [time shifts](https://github.com/ANNIEsoft/ToolAnalysis/pull/247/files#diff-d4eabec7462fa85c2e19bdf2d297940dba97c4bd279695a0cf33ba15eb4812b1R38) in the TimeClustering Tool? As always not a fan of hard-coded values; where do these numbers come from? Can they be expected to be stable?

**Comment by mnieslony** [comment]
Hi Marcus,
The channels are defined based on a time shift between the two CAMAC crates for the MRD (one crate in rack 7, one crate in rack 8). So channels which are recorded by TDCs in the first CAMAC crate are shifted in time with respect to the channels in TDCs of the other CAMAC crate. Since there does not seem to be any geometrical correlation between the shifted channels (just this electronic mapping correlation), I think that the shift is somehow intrinsic to the electronics setup. I did not observe any change in this shift over the period that I analyzed (data until May 2021) and I do not expect it to change for newer data, but it could be checked explicitly by looking at a couple of newer runs.

**Comment by marc1uk** [comment]
OK, thanks for the explanation. Perhaps there's a difference in cable lengths or an unbalanced delay in common stop signal going to the TDCs.

seems like we have a potential segfault if `layer_plots` is false in [MrdPaddleEfficiencyCalc.cpp:L371](https://github.com/ANNIEsoft/ToolAnalysis/blob/7c312c8d6bd0ff1d8bd195d5e8badc86eaaae056/UserTools/MrdPaddleEfficiencyCalc/MrdPaddleEfficiencyCalc.cpp#L371). Not sure why but the pointers `temp_exp_layer` and `temp_obs_layer` no longer get initialized to null, which seems like a regression (always good to initialise things). If `layer_plots` is false line 371 will then be dereferencing an uninitialized pointer. Likewise line 370 is dereferencing `temp_obs_layer`, which may be uninitialized. Should lines 370-375 be moved up into that `if` scope? 

Sorry to bounce it,  just not sure whether that's sufficient as it's a lot to parse. Otherwise looks good so hopefully if that's an ok fix it won't take a second and can be merged. :+1:

**Comment by mnieslony** [comment]
Hi Marcus,
You are right, the lines in question caused a segfault when `layer_plots` was set to `false`. I moved the lines inside the `if`-condition and tested the toolchain both with `layer_plots` set to `true` and `false`, both running fine now without segmentation faults.

**Comment by marc1uk** [comment]
Great, thanks a lot michael. That should be good to merge. :+1:

**Pull request merged**
