### PR TITLE
Find MRD Tracks data

### PR DESCRIPTION
**Pull request by mnieslony**
The tools `TimeClustering` and `FindMrdTracks` have been fully separated and need to be run sequentially from now on. Time clusters within the MRD data are found by the `TimeClustering` tool and passed on to the `FindMrdTracks` tool via the `CStore`. The `FindMrdTracks` tool then tries to fit tracks within those time clustered hits.
MRD tracks can now be fit both in data and MC, two exemplary toolchains can be found in `configfiles/MrdPaddleEfficiency`. MC files are read in via the `LoadWCSim` tool while data files are read in via the `LoadANNIEEvent` tool. Note that the `ANNIEEvent` boost stores need to be created beforehand from raw data by applying the `MRDDataDecoder` and `ANNIEEventBuilder` tools. [revised and finalised in PR 148]
The `FindMrdTrackFinder` tool uses `MrdTrackLib` libraries to actually perform the fit and draw the MRD event displays along with the fitted tracks. Since those libraries use the WCSim internal mapping for the PMTs, the channelkeys need to be converted to WCSim PMT IDs in the `TimeClustering` tool. For MC files, the mapping from channelkeys is achieved by using the autogenerated map from `LoadWCSim`. For data files, the mapping information is read in from an external file (MRD_Chankey_WCSimID.dat), which is also located in the same toolchain `MrdPaddleEfficiency`.

### CODE REVIEW

**Comment by marc1uk** [comment]
Thanks @mnieslony, this looks like a lot of work! I hadn't realised it would be that difficult to extend it for data files, so thanks for putting in the effort :+1: 
I'm afraid there's a bit much to go through thoroughly, but I trust it all works, and from a first skim i couldn't spot any issues.
One thing I am curious about: why do you track TFile users with 
`get_ok = m_data->CStore.Get("RootFileUsers",rootfileusers);`
and the like? I used this method for `TApplication` because an application can only have one TApplication: so the first Tool that tries to do so will make a TApplication, and others will subsequently (IIRC) receive the same one. But, if a Tool then closes that TApplication in it's Finalise while others downstream are still using it, that causes problems. I wouldn't anticipate any such trouble with TFiles, though....
A couple of minor issues I did spot:
In MrdPaddlePlot, it seems as though if a previous tool has registered a TFile, then the MrdPaddlePlot tool enables writing of it's histograms to a ROOT file, even if the user has asked for them not to be. That seems potentially unwanted?
It also looks like you may have forgotten to de-register MrdPaddlePlot from the rootfileusers list in it's `Finalise` method...

**Comment by mnieslony** [comment]
Hi @marc1uk,
No problem, it was actually kind of fun to implement the functionality of reading in data files. There are some supplementary changes in e.g. the `TimeClustering` tool where debugging histograms of the cluster times with different triggers (Beam/Cosmic) can be saved, so the PR might seem to entail more changes with respect to the original code than it actually does.
`TFiles`, yes... So the problem is the following: Suppose you have a ToolChain with Tool A and Tool B, then in Tool A you create a `TFile` in the `Initialise` step (together with some other ROOT objects like histograms). If you only had Tool A, there would be no issues, the histograms could be saved to the file in each `Execute` step or at the end in the `Finalise` step. If you now have another tool (Tool B) that also uses histograms or other ROOT objects, there will be a problem. ROOT associates the histograms to the `TFile` that is currently active (in this case the `TFile` created by Tool A), and remembers this association. Everything will be fine until the `Finalise` step of Tool A, where the respective objects of Tool A get saved to the file and then the file gets deleted. Since ROOT associated the histograms of Tool B with the `TFile` of Tool A, it will delete also those histograms (as a "feature" of `TFiles`). If you now want to access the histograms of Tool B in its `Finalise` step, the pointer will point to the deleted objects and the data stored in the histograms is lost. There might be a better way to do it though than to force the user to save the histograms and create a second `TFile` in Tool B (so the histograms get associated to that `TFile`), I agree. Maybe one should just not create the histograms at all in that case.
And thanks for noticing the missing de-registering of `MrdPaddlePlot` in the `Finalise` part, I'll add a commit with the change right away.

**Comment by marc1uk** [comment]
Hi Michael,
The tfile commit will always delete the mrdvisfile. Is that what you intended? I can't remember whether this is a shared file or not.
In either case, there's a much simpler solution for TFiles: after creating a new TFile, set it as active, create all the objects you want in it (and associated with it), and then set the directory back to gROOT so that future objects will not be associated with it.  
```
TFile* fout = new TFile("MyOutputFile.root","RECREATE");
fout->cd(); // technically probably redundant
TTree* mytree = new TTree("Atree","SomeDescriptor");
TH1D* myHisto = new TH1D("MyHisto","Oh hai",100,0,100);
gROOT->cd();
```
I would then also call `fout->cd();` before doing any `myHisto->Write()` or `mytree->Write()` calls, just to be safe. With this pattern any tool can create as many files as they like and they won't interfere.

**Comment by brichards64** [comment]
please pull in the upstream to run travis

**Comment by mnieslony** [comment]
Hi Marcus,
Thank you for this suggestion, that makes the organization of ROOT-files & ROOT-related objects much easier! I implemented the structure with switching to `gROOT` after handling the affected objects and removed the `rootfileusers` variable in the `CStore`, since it's not of much use in that case.

**Comment by brichards64** [comment]
Hi Michael can you resolve the conflicts

**Comment by mnieslony** [comment]
Hey Ben, the conflicts for this PR should be resolved now.

**Pull request merged**
