### PR TITLE
Addition of tools to load Phase II DoE data into reconstruction

### PR DESCRIPTION
**Pull request by pershint**
This pull request adds tools for reading the DoE ntuple data into the ToolAnalysis reconstruction tools.  Two new tools are introduced:

DigitBuilderDoE: Reads in the PMT/LAPPD hit information, as well as the true muon vertex information, into the RecoEvent store
EventSelectorDoE: Flags events that do not have muons in the defined fiducial volume, as well as muons with zero track length in MRD

ROOT's GenVector library needed to be added to the makefiles to use TLorentzVector.  This has been done in both the FNAL and default makefiles.

### CODE REVIEW

**Comment by pershint** [comment]
Initially had merge conflicts with ordering of terms in Factory.cpp and Unity.cpp.

**Comment by brichards64** [comment]
Hi Teal, looks good you seem to have forgotten the aim links in the main directory to your new toolvhain configurations. Was this on purpose?

**Comment by pershint** [comment]
Hey Ben, yeah I haven't been adding the aim links for all of the configuration files I've made.  I didn't want to clutter the main directory with them all.  Eventually I will have one aim link specifically targeting the main reconstruction chain.  Does that sound reasonable?

**Comment by brichards64** [comment]
Ok that sounds fine. I just wanted to check you hadn't forgotten.

Approved for merger then

**Pull request merged**
