### PR TITLE
PhaseIITeeMaker Update

### PR DESCRIPTION
**Pull request by mnieslony**
Some updates for the PhaseIITreeMaker tool are included in this PR. In particular, both the `PhaseIITreeMaker` tool and the `ClusterClassifiers` tool are made MC-compatible with a configurable parameter indicating whether one is looking at data or MC. Furthermore, the `ClusterFinder` tool modifies the MC-detected hit times in a way to make them more conform with data (2ns resolution, combine multiple hits in a short time window to one pulse)
The `BeamClusterAnalysis` toolchain which makes extensive use of the `PhaseIITreeMaker` tool has been updated, and a MC version of the same toolchain (`BeamClusterAnalysisMC`) has been added.

### CODE REVIEW

**Comment by marc1uk** [comment]
i notice that in your LoadWCSim PR you added two new maps `pmt_tubeid_to_channelkey_data` and `channelkey_to_pmtid_data`, and [here](https://github.com/ANNIEsoft/ToolAnalysis/pull/203/files#diff-0dbc5f903840da341edc8909ee2a3e89a0a37fd37be8825e294bf8cfaa6d2187R29) you're loading both the new map and the inverse map for the _old_ map. ... either that's a mistake, or (as a guess) you're unmapping channelkey back to WCSim PMTID, then re-mapping WCSim PMTID back to another channelkey. Which really suggests you should have just used a different channelkey to begin with.

**Comment by marc1uk** [comment]
Hold up, is that a [third](https://github.com/ANNIEsoft/ToolAnalysis/pull/203/files#diff-d4eabec7462fa85c2e19bdf2d297940dba97c4bd279695a0cf33ba15eb4812b1R129) set of PMT ID mappings now?

**Comment by marc1uk** [comment]
I guess I have no other specific issues with this, one general question from the description; it seems like there's an increasing amount of code complexity being employed to handle differences between MC and Data. As the person probably most familiar with the code, how much divergence/duplication is there, and can it be simplified? Maybe it's a bit off-topic from this PR to overhaul it all, but every time this comes up I'm concerned the situation gets worse.

**Comment by mnieslony** [comment]
@marc1uk 
> Hold up, is that a [third](https://github.com/ANNIEsoft/ToolAnalysis/pull/203/files#diff-d4eabec7462fa85c2e19bdf2d297940dba97c4bd279695a0cf33ba15eb4812b1R129) set of PMT ID mappings now?

Ah yes, since the MRD IDs are separate from the other PMT IDs they also needed a separate channelkey->pmtid map for data/MC. 

> I guess I have no other specific issues with this, one general question from the description; it seems like there's an increasing amount of code complexity being employed to handle differences between MC and Data. As the person probably most familiar with the code, how much divergence/duplication is there, and can it be simplified? Maybe it's a bit off-topic from this PR to overhaul it all, but every time this comes up I'm concerned the situation gets worse.

I think the most important issue is the `MCHit`/`Hit` difference since this bloats the code in every tool that uses any Hit information, be it MRD Hits or conventional PMT Hits. Maybe we want to migrate to just having `Hit` objects for all cases, and then just have some optional variables that are only filled if it's coming from the simulation. Similarly, it might be good to just store a variable in the `CStore` indicating whether a data or MC file was loaded, and then the tools check there what they are dealing with instead of having to configure every tool on its own.

The second issue would be the different channelkey mappings that were already addressed in the discussion for PR #202 . It would make sense to stop the dynamic channelkey loading in the simulation and just use the same keys in both cases. This would get rid of some of the mapping complications that we currently have. Maybe it would also make sense in a next step to get rid of the use of wcsim IDs completely and only use channelkeys, but this would then also need changes in `MrdTrackLib` for example.

I think those two changes would already help a lot, but should probably be covered in a separate PR since they require that one goes through all the tools that currently have MC/data toggles and adjust all of them (alongside testing).

**Comment by marc1uk** [comment]
> Ah yes, since the MRD IDs are separate from the other PMT IDs they also needed a separate channelkey->pmtid map for data/MC. 

In what sense are they separate? The [standard LoadGeometry config](https://github.com/ANNIEsoft/ToolAnalysis/blob/Application/configfiles/LoadGeometry/LoadGeometryConfig)† seems to have entries for both tank and MRD mapping files, and LoadWCSim also makes both maps at once. Why do other tools need to load new maps?
I think now that we have have a fixed `MC->Data` mapping the WCSim TubeID should be added to theLoadGeometry csv files and the channelkey map just created by the LoadGeometry tool; then no other tools should need to define maps at all, right?

> Maybe it would also make sense in a next step to get rid of the use of wcsim IDs completely and only use channelkeys, but this would then also need changes in MrdTrackLib for example.

We'll always need one map to exist for LoadWCSim to know what channelkey to use, so MrdTrackLib can always use that to go back to map back to TubeID.

† we seem to have a duplicate LoadGeomtry config [here](https://github.com/ANNIEsoft/ToolAnalysis/blob/Application/configfiles/BeamClusterAnalysis/LoadGeometryConfig)....I know it's not _quite_ standard practice to share one config file between toolchains like this, but I think it's been working so far. Is there a reason it got duplicated this time?

>  Maybe we want to migrate to just having Hit objects for all cases, and then just have some optional variables that are only filled if it's coming from the simulation. 

The MCHit class derives from the Hit class, so the idea was always to have a vector of `Hit*`s, which can then be `dynamic_cast` to `MCHit*` when appropriate. So for LoadWCSim, add a declaration [here](https://github.com/ANNIEsoft/ToolAnalysis/blob/Application/UserTools/LoadWCSim/LoadWCSim.cpp#L208)
```
    std::map<unsigned long, std::vector<Hit*>> Hits;  // use persist=false to avoid duplicating on disk
```
and then populate it [here](https://github.com/ANNIEsoft/ToolAnalysis/blob/Application/UserTools/LoadWCSim/LoadWCSim.cpp#L547):
```
    if(MCHits->count(key)==0){
        MCHits->emplace(key, std::vector<MCHit>{nexthit});
        Hits->emplace(key, std::vector<Hit*>{&MCHits->at(key).back()});
    } else {
        MCHits->at(key).push_back(nexthit);
        Hits->at(key).push_back(&MCHits->at(key).back());
    }
```

And something similar for real data and LoadANNIEEvent to populate the same `std::map<unsigned long, std::vector<Hit*>>` in all cases. Then downstream Tools have just one place to access the `Hits`, and they can cast to MCHit when necessary.

> Similarly, it might be good to just store a variable in the CStore indicating whether a data or MC file was loaded

That's the [MCFlag](https://github.com/ANNIEsoft/ToolAnalysis/blob/Application/UserTools/LoadWCSim/LoadWCSim.cpp#L709) isn't it?

> I think those two changes would already help a lot, but should probably be covered in a separate PR since they require that one goes through all the tools that currently have MC/data toggles and adjust all of them (alongside testing).

Yeah, on the one hand this PR introduces new maps that I still don't understand the need for, but perhaps overhauling the lot in one separate PR is the better way to go than worrying about it here.

**Pull request merged**
