### PR TITLE
FindMrdTracks Tool: put tracks into a vector of BoostStores

### PR DESCRIPTION
**Pull request by marc1uk**
Fix FindMrdTracks to fill found tracks into a vector of single-entry BoostStores instead of a multi-entry BoostStore.
Finish MrdPaddlePlot tool for demonstrating MRD Track retrieval and drawing.

Add ps component to TimeClass, required for precision of track times for reconstruction.

Add hit time plot to the set of debug plots for LoadWCSimLAPPD tool.

### CODE REVIEW

**Comment by brichards64** [comment]
Hi Marcus,

I saw that you edited some data model classes and that some of the things on this PR follow what was discussed on slack.

so two questions

1) have the discussions on slack solidifed yet such that this is the right version and therfore mergable

2) have you updated the goodle doc with any new data model classes and updated the old ones you have changed so it maps correctly (as per the new policy)

**Comment by marc1uk** [comment]
1. I've pestered the #all_software channel in slack to hopefully get confirmation.
2. I don't have permissions to update the data model classes on the google spreadsheet.

**Comment by brichards64** [comment]
dont forget to let me know what you need to update on the spreadsheet wso we can do it and then get this merged

**Comment by marc1uk** [comment]
The only things that need to change on the spreadsheet are the removal of Tpsec members of LAPPDHit and LAPPDPulse on the 'Hit' tab.

**Comment by marc1uk** [comment]
The only things that need to change on the spreadsheet are the removal of Tpsec members of LAPPDHit and LAPPDPulse on the 'Hit' tab.

**Pull request merged**
