### PR TITLE
LAPPD Event Filtering

### PR DESCRIPTION
**Pull request by rory42edwards**
Added Tool & associated ToolChain for filtering out events containing LAPPD data from processed data files.

### CODE REVIEW

**Comment by marc1uk** [comment]
Hi Rory,
As discussed in the meeting, I think the changes here are a little opaque, so could do with some explanation for myself and other users. It seems like you're setting either the `EventNumber` or `LocalEventNumber` of the ANNIEEvent Store. Without trauling through the code, though, I'm not clear where those are used, where the values you override them with come from, or why this is required. I think some clear documentation is necessary - ideally in the LoadANNIEEvent tool README. 

There's another couple of things, though. Firstly [this line](https://github.com/ANNIEsoft/ToolAnalysis/pull/215/files#diff-4cf77a07dd68eb122942a0abf6a6f009558f2c2c368240bce715bcf52446bcb7R191) changes the global event number regardless of the value of the new setting - it's not inside the scope of the if statement. Is that intended? 

The other thing is that the [default value](https://github.com/ANNIEsoft/ToolAnalysis/pull/215/files#diff-4cf77a07dd68eb122942a0abf6a6f009558f2c2c368240bce715bcf52446bcb7R17) for this new variable is 0, but your changes are introduced whenever the variable is false; i.e. this changes the default behaviour. Anyone else with a ToolChain that uses the LoadANNIEEvent tool will therefore get this new behaviour unless they explicitly add in a new variable to prevent that. Obviously that can throw off other analysers, so unless there's good reason this should be the new default, please update the behaviour. 

(I would personally use `true/false` rather than `0`, to make the code more clear that it's a boolean option. You may also think about switching your code so that some action is taken when something is true, rather than not taken when something is false, since that's generally easier to parse. But these are obviously minor niggles.)

And of course you'll need to pull in upstream changes to address the conflicts.

**Comment by marc1uk** [comment]
Alright uhh, i can see you've pushed new commits to this branch and there are no longer any conflicts. Is this ready to merge?

For posterity it would be great to comment here on the changes made to address comments. Are all those commented above now resolved? For example, I'm a little annoyed that the links for referencing lines seem to have broken, so i can't see for example which line i was referring to in:
> Firstly [this line](https://github.com/ANNIEsoft/ToolAnalysis/pull/215/files#diff-4cf77a07dd68eb122942a0abf6a6f009558f2c2c368240bce715bcf52446bcb7R191) changes the global event number regardless of the value of the new setting - it's not inside the scope of the if statement. Is that intended?

so I guess I'll assume that's now resolved...

**Comment by rory42edwards** [comment]
I did go through your comments and completed your suggestions, but since
you merged in the branch to my fork and resolved the conflicts I haven't
touched it. I haven't updated the documentation (ie pretty sure the README
is still just the template) - so not yet ready to merge to the main
anniesoft

**Comment by marc1uk** [comment]
ok, cool. Well if you happen to be twiddling your thumbs later tonight and there's not much more to do it would be nice to have a clean sweep of 0 PR's for tomorrow's software session.

**Comment by rory42edwards** [comment]
I believe this is now ready to merge - tested on the gpvm machines (it compiled when I used an overlay) and works as it should. i removed the "run_on_filtered" from the config files and made the LoadANNIEEvent tool just check if the LocalEventNumber exists already in the ANNIEEvent store, so the user doesn't need to worry about it

**Pull request merged**
