### PR TITLE
New Data Classes and a New Tool

### PR DESCRIPTION
**Pull request by wetstein**
Added two data classes:
1) LAPPDHit which inherits from Hit and stores position, as well as time, and has a variable for storing fractions of nanoseconds
2) LAPPDPulse which also inherits from Hit, and consists of the reconstructed pulses. It adds two variables to the Hit class: the channelID of the pulse and the fraction of a nanosecond for the pulse time

I also added a new tool that generates simulated LAPPDHits (GenerateHits) to pass along to the LAPPDSim tool, and modified the LAPPDSim tool to use those hits from the GenerateHits tool

### CODE REVIEW

**Comment by brichards64** [comment]
Hi Matt, as you can see your pull request didnt pass the travis compilation test.

looks like you forgot to git add the new data class LAPPDHit.h

**Comment by brichards64** [comment]
and you forgot to git add the new GenerateHits tool as well. 

BTW if this tool is for generating LAPPD hits you may want to call it GenerateLAPPDHits or something less generic.

**Comment by wetstein** [comment]
Hey Ben, I just added the missing classes/tools. How do I resubmit?

ALso, I purposely left the GenerateHits tool generic, so the name was intentional...I wanted it to be a place where users could generate hits in multiple photodtetectors.

**Comment by brichards64** [comment]
Hi Matt, looks good now seems to be compiling.

However you seem to git added include/LAPPDHit.h and include/LAPPDPulse.h which dont need to be added and just cluter things. Could you remove them.

thanks

Ben

**Pull request merged**
