### PR TITLE
Add Load WCSim, Print WCSim and FindMrdTracks tools

### PR DESCRIPTION
**Pull request by marc1uk**
Add the ability to load wcsim files, print the loaded event information and find MRD tracks, which are added to a new Boost store.

### CODE REVIEW

**Comment by brichards64** [comment]
So this didnt pass the compilation tests as can be seen by it failing the checks above. That's not necesarily a problem i kind of expected it to fail because you have added a new dependancy and the build test doesnt know about it. 

So i will have to check this one manually and add it to the base images. I'l try and do this soonish but ill probably have a few coments regarding odd changes

**Comment by marc1uk** [comment]
Err, yeah. Maybe I need to add the git pull command to make it pull the LibWCSim and LibFindMrdTracks repos in along with ToolDAQ and zmq. Once those are done it worked fine for me on the gpvms. 
Let me know about any other oddities.

**Comment by brichards64** [comment]
Ill try and get some cycles today to test this out. Might also be an idea to create and example for reading in a Wcsim file and printing some stuff out

**Comment by brichards64** [comment]
ok had a look at this and nothing compiles. on the stardard version. Looks like the WCsim lib also needs Geant4 is that correct?

**Comment by brichards64** [comment]
I am very very pleased to finally be closing this PR.

thanks for all your work marcus

**Pull request merged**
