### PR TITLE
EventDisplay Update

### PR DESCRIPTION
**Pull request by mnieslony**
The `EventDisplay` tool was updated to work with both `ANNIEEvent` and `RecoEvent` objects. Additional features were added, specifically 
* the ability to plot multiple rings if there was more than one ring in the event
* the ability to select the next event number interactively
* the ability to save the event displays as canvases in root files instead of images
* the ability to plot only events that passed a specified `EventSelection`

Furthermore, the tool was updated to also work with data files instead of only Monte Carlo files. An exemplary toolchain to plot data files can be found in `/configfiles/EventDisplay/Data`. Note that the data files need to be produced via the `DataDecoder` toolchain from raw files and that the Pull Requests 147 and 148 are needed for this toolchain to run correctly.
There were some minor changes in other tools:
* `MCRecoEventLoader`: Added the ability to calculate the number of rings based on the true energies of the primary particles taken from MC
* `MCParticleProperties`: Added the property `projectedHitMrd` to the `MCParticle` object, which specifies whether the (extended) trajectory of a primary particle were to hit the MRD. Additionally, there is now the `PdgMassMap` object added to the `CStore` which contains a mapping from PDG numbers to their masses.
* `LoadWCSim`: The event number to be loaded can now be set by a different tool if desired. An example of this usage can be seen in the `EventDisplay` tool.
* ` HitCleaner`: The `FilterDigitList` object is now loaded into the `RecoEvent` store.
* `EventSelector`: More selection cuts were added, namely:
  - IsElectron
  - IsMuon
  - IsSingleRing
  - IsMultiRing
  - ProjectedMRDHit
  - MCEnergyCut
* `DigitBuilder`: The minimum charge on a PMT to create a digit can now be specified in the configuration file.
* `LoadANNIEEvent`: Similarly to `LoadWCSim`, other tools can influence which event number is loaded by setting the relevant information in the `CStore`.

### CODE REVIEW

**Comment by brichards64** [comment]
please pull in the upstream to run travis

**Comment by brichards64** [comment]
hi michael conflicts on this one too

**Comment by brichards64** [comment]
I don't see the need for the makefile changes?

whats their purpose? you seem to ahve uncommented lines that should still be commented out

**Comment by mnieslony** [comment]
Hi Ben,
I accidentally committed the changes in the Makefile, sorry about that. I reversed the changes in the latest commit.

**Pull request merged**
