### PR TITLE
Cluster (of hits) finding tool

### PR DESCRIPTION
**Pull request by vfischer**
Adding a new tool to find clusters of hits and pass them as a map in the CStore.

### CODE REVIEW

**Comment by brichards64** [comment]
Hi Vincent looks like it errored due to missing PMTDataDecoder.h

**Comment by vfischer** [comment]
I forgot to add it to this pull request (I made another one but canceled it) but you should pull Teal's change before this one since I copied his branch and started working from there

**Comment by brichards64** [comment]
teals has been merged in now. so please resolve conflicts and issues and try again

**Comment by vfischer** [comment]
Ok I fixed the conflicts. It should be ready to be merged now

**Pull request merged**
