### PR TITLE
Correction of ANNIEEventBuilder::Correct8nsOffset

### PR DESCRIPTION
**Pull request by JohannMartyn**
The number of timestamp entries was incorrect in ANNIEEventBuilder::Correct8nsOffset: the most recent entries, which are probably still in progress were not excluded. 
This is taken into account correctly in ANNIEEventBuilder::Correct8nsOffsetRaw, from which the code has been copied.

### CODE REVIEW

**Comment by marc1uk** [comment]
hi johann. Looks good, just out of curiosity, what does it mean when you say the timestamps are incorrect, because they're proabably still in progress? This seems to build a vector of PMT Hit timestamps. Surely a PMT hit (and in particular the time at which it happened) is a fairly atomic object that either exists, and has a correct timestamp, or doesn't? Are we building PMT Hits with invalid timestamps? And then correcting those timestamps at some later point? It seems a bit odd to me.

**Comment by JohannMartyn** [comment]
In the function "ANNIEEventBuilder::Correct8nsOffset", there is a local vector std::vector<uint64_t> timestamps_tank, which is filled with the uint64_t time variables from the std::map<uint64_t, std::map<unsigned long,std::vector<Hit>>*> *InProgressHits map.

  for(std::pair<uint64_t,std::map<std::vector<int>, std::vector<uint16_t>>> apair : *InProgressTankEvents){
    uint64_t PMTCounterTimeNs = apair.first;
    timestamps_tank.push_back(PMTCounterTimeNs);
  }

In later loop "for (int i_timestamp = 1; i_timestamp < timestamps_tank.size(); i_timestamp++)"
 the "std::map<unsigned long,std::vector<Hit>>" from InProgressTankEvents is then also accessed trough 
"int waveforms_first = int(InProgressHits->at(FirstTS)->size());
int waveforms_second = int(InProgressHits->at(SecondTS)->size());"
Here FirstTS and SecondTS correspond to the apair.first values of the above loop, filled in the timestamps_tank vector.
 
This can give a std::map out_of_range exception if we go up to timestamps_tank.size() because the "InProgressHits->at(SecondTS)" may not exist yet.

For this reason I copy pasted the solution to this problem from  the "ANNIEEventBuilder::Correct8nsOffsetRaw" function, which constrains the loop to number_entries, instead of the full  timestamps_tank.size().
"
  //Exclude the last five (most recent) entries, since those are probably still in progress
  int number_entries = (timestamps_tank.size() > 6)? timestamps_tank.size() - 5 : 1;
  if (force_all_entries) number_entries = (int) timestamps_tank.size();
"

In this sense the timestamps are not incorrect, but rather the timestamps are used as a key to a pointer which may not exist yet.
Of course my interpretation may be not correct, but the std::map out_of_range exception does not exist anymore.

**Comment by marc1uk** [comment]
hmm. 
OK. first, quick aside; for readability you can use single backticks for `inline code` and three backticks to delineate 
```
blocks of code
```
(this also works on slack, btw). 

So firstly it builds a vector of timestamp keys present in `InProgressTankEvents`, but then later uses that timestamp key on `InProgressHits` (think you got those mixed up in your post), and there may not be a corresponding entry.

The next question is, what is `InProgressHits`, and where/when is it being filled? Is it expected to have an entry for _every_ `InProgressTankEvents` entry? Is it understood and expected that such an entry may not exist by the time your Tool tries to get it? 

My first concern is that unless this is understood and expected, it _could_ be a symptom of a subtle bug that we're making even harder to find by hiding it.

My second concern is that stopping .... uhh, let's say 5 entries short? :man_shrugging: ... without any real justification of that may work for now, but such workarounds can be brittle. It may work for everything you run it on, but perhaps another analyser in 6 months time finds that 1 in 1000 of their jobs crashes, because 5 happens not to be a big enough buffer for them. Then they have to waste a bunch of time trying to figure out what's throwing this random out_of_range exception they're seeing, and what's the underlying cause.

I think a better workaround, if we're happy that this isn't symptomatic of something unexpected, is to simply check that the entry exists before trying to access it:
```
int waveforms_first=0, waveforms_second=0;
if(InProgressHits->count(FirstTS)) waveforms_first = int(InProgressHits->at(FirstTS)->size());
if(InProgressHits->count(SecondTS)) waveforms_second = int(InProgressHits->at(SecondTS)->size());
```

**Comment by JohannMartyn** [comment]
Okaye, I am trying to implement your suggestion. For this reason I still need to re-process some Runs and check if everything works as intendend.
I will let you know when its done, and probably open a new merge  request with the new changes.

**Pull request closed without merging**
