### PR TITLE
Added config files for MuonFitter to CC_MC_RECO_ntuple Toolchain

### PR DESCRIPTION
**Pull request by jminock**
Added MuonFitter configfile and addition to PhaseIITreeMaker. Documentation for MuonFitter and how to use it is coming

### CODE REVIEW

**Comment by marc1uk** [comment]
I guess this is associated with #293 , and would probably have been better to have been part of the same PR.
In the config file I see `TankTrackFitFile tanktrackfitfile_r0.0_RNN.txt` - but that file isn't part of the PR and appears to be in a local directory (i.e. not on /pnfs/annie/persistent).
Is that an important file? I'm not really able to follow my way through the 2.5k lines of code, but it seems like the tool reports that it won't work in Reco mode (which would seem like the useful mode for a fitter) without it....
What kind of file is this? How is it generated? If it's a required input, can we
1. add something that generates it (and comments in the Tool README)
2. add a copy somewhere on pnfs? 

Also, this adds the Tool into the CC_MC_RECO_ntuple toolchain, and it's great to have it somewhere, but are all 17 of those files required for this Tool to work? It would be good to have a minimal demonstration, as well as integration into "standard" analysis toolchains.

**Comment by marc1uk** [comment]
based on the readme in #295 it seems like perhaps this RNN file may be in `/pnfs/annie/persistent/simulations/models/MuonFitter/` ?

**Comment by jminock** [comment]
Hi Marcus,

The `TankTrackFitFile tanktrackfitfile_r0.0_RNN.txt` is generated by one of the scripts, `Fit_data.py` from #290. This script requires `ev_ai_eta_R0.0.txt` which is generated by MuonFitter when it is not ran in RecoMode. Each run number and part number of the ev_ai_eta file must correspond to run number and part number of the tanktrackfitfile, which corresponds to the wcsim/data file number and part number.  This is all included in the MuonFitterREADME.md from #295 

I will create a persistent directory for the ev_ai_eta and tanktrackfit files as a part of production, when I get to the ToolAnalysis step of MC production. If someone wishes to run this Tool in RecoMode, they will have to run generate the above files themselves for their respective wcsim/data set. Instructions for doing so are included in #295 

Not all Tools in CC_MC_RECO are required for this Tool to work, but nearly all of those Tools are required for a finished MC ntuple set to analyze. It's my understanding that CC_MC_RECO is a standard analysis toolchain because it is the only toolchain being used for CC XSec analysis. 
A minimal demonstration toolchain sounds nice. Julie never included that. Creating a minimal toolchain for it would require some additional time on my part; so, if there is enough interest among collaborators, I can pause and look into that.

Thank you,

James

**Comment by marc1uk** [comment]
> I will create a persistent directory for the ev_ai_eta and tanktrackfit files as a part of production, when I get to the ToolAnalysis step of MC production.

Sounds good, if we have standard MC datasets, it seems sensible to make these files standard too so people don't have to do the two-step regime. Please include that in the ToolChain readmes so that people know where to look.

> Not all Tools in CC_MC_RECO are required for this Tool to work, but nearly all of those Tools are required for a finished MC ntuple set to analyze. 

I guess this is the same as defining a minimal toolchain for the MuonFitter tool, but if the toolchain is running twice it would be good to ensure we aren't running upstream tools in the first iteration that aren't used by MuonFitter in `recomode 0`.

It would probably also be good to define which config variables of the MuonFitter Tool are used in which modes.

**Comment by jminock** [comment]
I'll look into that for non-Reco mode and ping you once I add documentation for it. Thank you!

**Comment by jminock** [comment]
PR #316 provides minimal demonstration Toolchain. Both reco and non reco modes use the same Tools. Documentation for this added to the README in #316

**Pull request merged**
